config/routes.rb
Rails.application.routes.draw do
  resources :charities

  resources :jobs

  root 'home#index'

end

app/models/charity.rb
class Charity < ActiveRecord::Base
end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController
  before_action :set_charity, only: [:show, :edit, :update, :destroy]

  # GET /charities
  # GET /charities.json
  def index
    @charities = Charity.all
  end

  # GET /charities/1
  # GET /charities/1.json
  def show
  end

  # GET /charities/new
  def new
    @charity = Charity.new
  end

  # GET /charities/1/edit
  def edit
  end

  # POST /charities
  # POST /charities.json
  def create
    @charity = Charity.new(charity_params)

    respond_to do |format|
      if @charity.save
        format.html { redirect_to @charity, notice: 'Charity was successfully created.' }
        format.json { render :show, status: :created, location: @charity }
      else
        format.html { render :new }
        format.json { render json: @charity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charities/1
  # PATCH/PUT /charities/1.json
  def update
    respond_to do |format|
      if @charity.update(charity_params)
        format.html { redirect_to @charity, notice: 'Charity was successfully updated.' }
        format.json { render :show, status: :ok, location: @charity }
      else
        format.html { render :edit }
        format.json { render json: @charity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charities/1
  # DELETE /charities/1.json
  def destroy
    @charity.destroy
    respond_to do |format|
      format.html { redirect_to charities_url, notice: 'Charity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charity
      @charity = Charity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def charity_params
      params.require(:charity).permit(:organization, :year, :duties)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:company, :start_year, :end_year, :duties)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charities_helper.rb
module CharitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/charities/_form.html.erb
<%= form_for(@charity) do |f| %>
  <% if @charity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charity.errors.count, "error") %> prohibited this charity from being saved:</h2>

      <ul>
      <% @charity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :organization %><br>
    <%= f.text_field :organization %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :duties %><br>
    <%= f.text_area :duties %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charities/edit.html.erb
<h1>Editing charity</h1>

<%= render 'form' %>

<%= link_to 'Show', @charity %> |
<%= link_to 'Back', charities_path %>

app/views/charities/index.html.erb
<h1>Listing charities</h1>

<table>
  <thead>
    <tr>
      <th>Organization</th>
      <th>Year</th>
      <th>Duties</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @charities.each do |charity| %>
      <tr>
        <td><%= charity.organization %></td>
        <td><%= charity.year %></td>
        <td><%= charity.duties %></td>
        <td><%= link_to 'Show', charity %></td>
        <td><%= link_to 'Edit', edit_charity_path(charity) %></td>
        <td><%= link_to 'Destroy', charity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Charity', new_charity_path %>

app/views/charities/new.html.erb
<h1>New charity</h1>

<%= render 'form' %>

<%= link_to 'Back', charities_path %>

app/views/charities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Organization:</strong>
  <%= @charity.organization %>
</p>

<p>
  <strong>Year:</strong>
  <%= @charity.year %>
</p>

<p>
  <strong>Duties:</strong>
  <%= @charity.duties %>
</p>

<%= link_to 'Edit', edit_charity_path(@charity) %> |
<%= link_to 'Back', charities_path %>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1>Sarah Butterworth</h1>
  <p>Your next awesome hire!</p>
</div>

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :start_year %><br>
    <%= f.number_field :start_year %>
  </div>
  <div class="field">
    <%= f.label :end_year %><br>
    <%= f.number_field :end_year %>
  </div>
  <div class="field">
    <%= f.label :duties %><br>
    <%= f.text_area :duties %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<h1>Listing jobs</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Start year</th>
      <th>End year</th>
      <th>Duties</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.company %></td>
        <td><%= job.start_year %></td>
        <td><%= job.end_year %></td>
        <td><%= job.duties %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @job.company %>
</p>

<p>
  <strong>Start year:</strong>
  <%= @job.start_year %>
</p>

<p>
  <strong>End year:</strong>
  <%= @job.end_year %>
</p>

<p>
  <strong>Duties:</strong>
  <%= @job.duties %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SarahResume</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class='navbar navbar-default navbar-fixed-top' role='navigation'>
    <div class='container'>
      <div class='pull-left'>
        Sarah Butterworth
      </div>
      <ul class="nav nav-tabs pull-right">
        <li class="active"><%= link_to 'Home',root_path %></li>
        <li><%= link_to 'Experience', jobs_path %></li>
        <li><%= link_to 'Charity Work', charities_path %></li>
      </ul>
    </div>
  </nav>
  <div class='container'>
    <div class='row'>
      <%= yield %>
    </div>
  </div>
</body>
</html>